#! /usr/bin/env bash

# Global constants
PINE_VERSION=1.0.0
FILE_NOT_FOUND_EX=2
LOG_FILE=/tmp/pine_logs/log.txt
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
SRC_PATH="$PWD"
GITIGNORE_REPO="https://github.com/github/gitignore.git"

# Import functions
source "${SCRIPTPATH}/paramparser.sh" # For parameter parsing
source "${SCRIPTPATH}/inc/error.sh" # For error handling
source  "${SCRIPTPATH}/custpathhandler.sh" # For handling custom dir

# Global variables
declare -A map # map for easy searching of names
declare -A dirNameMap # map for easy searching of names

# Updates all gitignore files in ${SCRIPTPATH}/gitignore
function update_config_files() {
    echo -e "Updating local configuration files...\n"
    if [[ -d ${SCRIPTPATH}/gitignore/.git ]]; then
	git -C "${SCRIPTPATH}/gitignore" pull origin master -ff && {

	    for f in ${SCRIPTPATH}/gitignore/*; do
		filename=$(basename "$f")
		newpath="${SCRIPTPATH}/gitignore/${filename,,}"
		# Use output redirection to prevent warning when content of repo is not changed
		mv "$f" "$newpath" &> /dev/null 
	    done

	    # Fix symlinks if any
	    for f in $(find ${SCRIPTPATH}/gitignore/. -type l); do
		originalLink=$(readlink $f)
		ln -sfT ${originalLink,,} ${f}
	    done
	} || {
	    echo "FATAL ERROR: Cloning failed"
	    exit
	}
    else
	echo "WARNING: Cannot find local .gitignore repository, clonning..."
	git clone "$GITIGNORE_REPO" "${SCRIPTPATH}/gitignore" && {
	    update_config_files
	} || {
	    echo "FATAL ERROR: Cloning failed"
	    exit
	}
    fi
}

# Checks if config files exists, if not download them
function check_and_update_config_files() {
    if [[ ! -d  ${SCRIPTPATH}/gitignore/.git ]]; then
	update_config_files
    fi
}

# Compile names to a list
function compile_names() {
    for gitignoreFile in ${SCRIPTPATH}/gitignore/*.gitignore; do
	filename=$(basename "$gitignoreFile") # remove path
	configName="${filename%.*}" # remove extension
	configName="${configName,,}" # to lowercase
 	name="$name $configName" # append to name list
    done
    echo "$name" > ${SCRIPTPATH}/names.list
}

function load_names() {
    if [ -f ${SCRIPTPATH}/names.list ]; then
	storedNames=`cat ${SCRIPTPATH}/names.list` > $LOG_FILE || throw $FILE_NOT_FOUND_EX  # Read compiled list
    else
	echo "WARNING: Names list not compiled"
	echo "use 'pine --help'"
	echo "INFO: Compiling names list"

	compile_names && echo "Names list compiled"
	load_names

	return
    fi
    
    # Compile names for map
    nameArr=($storedNames)
    for name in "${nameArr[@]}"; do
	map[$name]=1
    done
}

function search_name_in_list() {
    # Returns 1 if name passed is in compiled map
    if [ ${map["$1"]+_} ]; then
	return 0
    else
	return 1
    fi
}

print_version() {
    echo -e "Version: $PINE_VERSION"
}

function print_help() {
    echo "Pine : gitignore manager"
    print_version
    cat "${SCRIPTPATH}/HELP.txt"
}

# Check if config for $1 exist in .gitignore file
function check_for_existing_name {
    local gitignoreFile="${SRC_PATH}/.gitignore"
    currentcontent=$(<$gitignoreFile)

    echo "$currentcontent" | awk -v a="$1" -f ${SCRIPTPATH}/utilities/checkconfig.awk && {
	return 1
    } || {
	return 0
    }
}

# Adds config for $1 to gitignore file if it doesn't exist
function add_config_to_file() {
    check_for_existing_name $1 && {
	echo "ERROR: Configuration exists, skipping"
    } || {
	echo "Adding configuration for $arg"
	echo -e "#### ${1} ##########################" >> ${SRC_PATH}/.gitignore
	echo -e "#### DO NOT DELETE PRECEDING LINE" >> ${SRC_PATH}/.gitignore
	echo -e "#### PINE" >> ${SRC_PATH}/.gitignore
	cat "${SCRIPTPATH}/gitignore/${1}.gitignore" >> ${SRC_PATH}/.gitignore
	echo -e "#### DO NOT DELETE THIS LINE" >> ${SRC_PATH}/.gitignore
    }
}

# Prints all the config of the file 
function list_all_config() {
    echo "Following configurations found:"
    if [ ! -f "${SRC_PATH}/.gitignore" ]; then
	echo "ERROR: No .gitignore file found in current directory, Exiting"
    else
	cat "${SRC_PATH}/.gitignore" | awk -f ${SCRIPTPATH}/utilities/listallconfig.awk 
    fi
}

# Removes config for $1 from gitignore file  
function remove_config_from_file() {
    echo "Removing configuration for $arg"
    
    local gitignoreFile=${SRC_PATH}/.gitignore
    currentcontent=$(<$gitignoreFile)

    echo "$currentcontent" | awk -v a="$1" -f ${SCRIPTPATH}/utilities/remove.awk > ${SRC_PATH}/.gitignore
}


function init() {
    set -e
    
    # Checks the presence of config files
    check_and_update_config_files
    
    # Create a gitignore file, if it doesn't exists
    if [ ! -f ./.gitignore ]; then
	echo "INFO: Creating .gitignore file"
	touch ".gitignore"
    fi

    # Make directory for logs
    if [ ! -d /tmp/pine_logs ]; then
	mkdir -p /tmp/pine_logs
    fi
    
    load_names
    eval $(parse_params "$@") # Parse parameters

    # If any parameter is help, print help and exit
    if [[ $help ]]; then
	print_help
	exit
    fi


    # If any parameter is version, print version and exit
    if [ $version ] || [ $v ]; then
	print_version
	exit
    fi


    # If any parameter is update, update and exit
    if [ $update ] || [ $u ]; then
	update_config_files
	exit
    fi

    
    # If any parameter is for listing configs, list and exit
    if [ $list ]; then
	list_all_config 
	exit
    fi
    
    # Search each parameter
    for arg in "${ARGV[@]}"; do
	if [ $remove ] || [ $r ]; then
	    remove_config_from_file $arg
	else
	    search_name_in_list $arg && { # Return 1
		add_config_to_file $arg
	    } || { # Return 0
		echo "WARNING: configuration file for $arg not found"
	    }
	fi
    done
}

# Initialise script
init  "$@"
